import { Inter } from "next/font/google";
import "./globals.css";
import Web3Provider from "@/context/Web3Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider>
        {children}
        </Web3Provider>
       </body>
    </html>
  );
}
